from sqlalchemy.orm import Session

from app.models.alert import Alert
from app.models.incident import Incident
from app.models.log import Log

from app.services.incident_timeline_service import create_timeline_event
from app.services.incident_evidence_service import create_evidence
from app.services.audit_log_service import create_audit_log, resolve_audit_organization_id


def create_alert(
    db: Session,
    ip_address: str,
    threat_level: str,
    message: str,
    log: Log = None
):
    alert = Alert(
        ip_address=ip_address,
        threat_level=threat_level,
        message=message
    )

    db.add(alert)
    db.commit()
    db.refresh(alert)

    incident = Incident(
        incident_code=f"INC-{alert.id:06d}",
        title="Security Incident",
        description=message,
        threat_level=threat_level,
        priority="P2",
        status="OPEN",
        source_ip=ip_address,
        target="Unknown",
        confidence=90
    )

    db.add(incident)
    db.commit()
    db.refresh(incident)

    create_timeline_event(
        db=db,
        incident_id=incident.id,
        event="Incident Created",
        description="Incident automatically created from critical alert."
    )

    if log:
        create_evidence(
            db=db,
            incident_id=incident.id,
            filename="trigger_request.log",
            file_type="HTTP Request",
            description="Original request that triggered the incident.",
            url=log.url,
            method=log.method,
            status_code=log.status_code,
            user_agent=log.user_agent,
            ip_address=log.ip_address,
            risk_score=log.risk_score,
            detection_reason=log.detection_reason
        )

    create_evidence(
        db=db,
        incident_id=incident.id,
        filename="risk_analysis.log",
        file_type="Analysis",
        description="Risk analysis generated by Sentinel AI."
    )

    create_evidence(
        db=db,
        incident_id=incident.id,
        filename="incident_summary.json",
        file_type="JSON",
        description="Incident metadata snapshot."
    )

    create_audit_log(
        db=db,
        organization_id=resolve_audit_organization_id(db),
        user_id=None,
        action="CREATE_INCIDENT",
        resource_type="INCIDENT",
        resource_id=str(incident.id),
        description=f"Incident '{incident.incident_code}' created from alert {alert.id}.",
    )

    return alert


def get_recent_alerts(db: Session):
    return (
        db.query(Alert)
        .order_by(Alert.created_at.desc())
        .limit(5)
        .all()
    )